import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import os
import io
from dotenv import load_dotenv
from fpdf import FPDF

load_dotenv()

# We load environment variables for the SMTP credentials.
# If these are not configured, the emails will just print to console.
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USERNAME = os.getenv("SMTP_USERNAME", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")

def send_email(to_email: str, subject: str, message_body: str, attachment: bytes = None, attachment_name: str = None):
    if not SMTP_USERNAME:
        print("ATTENTION: SMTP_USERNAME is empty, cannot send real email.")
        return

    msg = MIMEMultipart()
    msg['From'] = SMTP_USERNAME
    msg['To'] = to_email
    msg['Subject'] = subject

    msg.attach(MIMEText(message_body, 'plain'))
    
    if attachment and attachment_name:
        part = MIMEApplication(attachment, Name=attachment_name)
        part['Content-Disposition'] = f'attachment; filename="{attachment_name}"'
        msg.attach(part)

    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        # Login with email and app password
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"Successfully sent SMTP email to {to_email}")
    except Exception as e:
        print(f"Failed to send email via SMTP: {e}")
        # Reraise so the API fails if SMTP is broken.
        raise e

def create_offer_letter_text(name: str, job_title: str) -> str:
    return f"""Dear {name},

We are thrilled to officially extend an offer for the {job_title} position at ShellKode! Your performance during the technical and HR rounds was outstanding.

Please find your official offer letter attached to this email as a PDF document.
Reply directly to this email indicating whether you ACCEPT or REJECT this offer. Based on your reply, we will move forward with your profile to the onboarding process.

Best regards,
ShellKode HR Recruitment Team
"""

def generate_shellkode_offer_pdf(name: str, job_title: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    
    # Place the ShellKode Logo in the top-right corner
    logo_path = os.path.join(os.path.dirname(__file__), "shellkode_logo.jpg")
    if os.path.exists(logo_path):
        pdf.image(logo_path, x=130, y=10, w=70) # Accommodates the wider 669x177 image
    
    # Push content down so it starts below the logo height
    pdf.ln(30)
    
    # Title
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(2, 173, 239) # #02ADEF Cyan
    pdf.cell(0, 10, "OFFICIAL OFFER OF EMPLOYMENT", new_x="LMARGIN", new_y="NEXT", align="C")
    
    # Body
    pdf.ln(15)
    pdf.set_font("helvetica", "", 12)
    pdf.set_text_color(50, 50, 50)
    
    body_text = f"Dear {name},\n\n" \
                f"We are extremely pleased to formally offer you the position of {job_title} at ShellKode. " \
                f"Throughout the interview process, we were very impressed by your skills, background, and alignment with our company values.\n\n" \
                f"We believe you will make a fantastic addition to the team and help us build the future of technology.\n\n" \
                f"Please reply back to the attached email indicating whether you formally Accept or Reject this offer so we may begin the final onboarding procedures.\n\n" \
                f"Sincerely,\n" \
                f"The Executive HR Team\nShellKode"
                
    pdf.multi_cell(0, 8, body_text)
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("helvetica", "I", 10)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, "This is an automated formal offer document generated by the ShellKode HR platform.", align="C")
    
    # Export to bytes instead of file
    return bytes(pdf.output())

def create_rejection_letter(name: str, job_title: str) -> str:
    return f"""Dear {name},

Thank you for your interest in the {job_title} position and the time you spent going through our assessment process.

Unfortunately, we regret to inform you that we will not be moving forward with your application. We have decided to pursue other candidates whose profiles more closely align with our current needs.

We wish you the best of luck in your future endeavors.

Best regards,
HR Recruitment Team
"""

def send_onboarding_welcome(name: str, email_to: str, password: str):
    portal_link = "http://localhost:3000/onboarding/login"
    body = f"""Dear {name},

Congratulations on accepting the offer! We are extremely excited to welcome you to the team.

To finalize your hiring process, we need you to sign into our Onboarding Portal and upload your necessary verification documents.

Onboarding Portal: {portal_link}
Your Username: {email_to}
Your Temporary Password: {password}

Once you have uploaded all your documents (Photo, PAN Card, Aadhar, Degree Certificate, Experience Letter, Bank Details), our AI evaluation system and HR team will instantly review them to clear your joining date.

Welcome aboard!
ShellKode HR Recruitment Team
"""
    send_email(email_to, "Welcome to Onboarding! Your Credentials Inside", body)

def send_onboarding_completed(name: str, email_to: str):
    body = f"""Dear {name},

Great news! Our HR Recruitment Team has successfully verified all your onboarding documents.

Your onboarding process is now marked as 100% COMPLETE. 
You are fully cleared for your joining date. Our team will reach out to you shortly with the final orientation details and day-one agenda.

Congratulations once again, and welcome aboard!

Warm Regards,
ShellKode HR Recruitment Team
"""
    send_email(email_to, "Onboarding Verification Completed & Approved!", body)

def send_application_received(name: str, email_to: str, job_title: str):
    body = f"""Dear {name},

Thank you for applying to the {job_title} position at ShellKode!

We have successfully received your application. Our recruitment team will review your profile and get back to you shortly if your qualifications match our current needs.

We appreciate your interest in joining our team!

Best regards,
ShellKode HR Recruitment Team
"""
    send_email(email_to, f"Application Received: {job_title} at ShellKode", body)
